---
apiVersion: xl-deploy/v1
kind: Applications
spec:
- directory: Applications/Java
  children:
  - name: PetPortal
    type: udm.Application
    children:
    - name: 1.0.4
      type: udm.DeploymentPackage
      children:
      - name: petclinic
        type: jee.War
        scanPlaceholders: true
        file: !file "artifacts/PetClinic.war"
      - name: testPage
        type: smoketest.HttpRequestTest
        url: '{{smoke.test.url}}'
        expectedResponseText: '{{TITLE}}'
