apiVersion: xl-deploy/v1
kind: Environments
spec:
- directory: Prod
  children:
  - directory: AsCode
    children:
    - name: PetClinic Dictionary
      type: udm.Dictionary
      entries:
        TITLE: devops
        logFilePath: /dev/null
        logRootLevel: ERROR
        title: devops
        logLevel: ERROR
        timeout: 30
        smoke.test.url: http://deployit.vm:13080/petclinic/index.jsp
        tests2.ExecutedHttpRequestTest.url: '{{smoke.test.url}}'      
    - name: PetClinic DB Dictionary
      type: udm.Dictionary
      entries:
        tomcat.DataSource.driverClassName: com.mysql.jdbc.Driver
        tomcat.DataSource.url: jdbc:mysql://localhost/petclinic
        tomcat.DataSource.username: scott
        tomcat.DataSource.context: petclinic
      encryptedEntries:
        tomcat.DataSource.password: passwor
  - name: Tomcat-Prod-AsCode
    type: udm.Environment
    members:
    - ~Infrastructure/Prod/host-vm/tomcat/tomcat.vh
    - ~Infrastructure/Prod/host-vm/sql-db
    - ~Infrastructure/Prod/host-vm/tomcat
    - ~Infrastructure/Prod/host-vm/testRunner
    - ~Infrastructure/Prod/host-vm
    dictionaries:
    - ~Environments/Prod/AsCode/PetClinic Dictionary
    - ~Environments/Prod/AsCode/PetClinic DB Dictionary
