apiVersion: xl-deploy/v1
kind: Deployment
spec:
  package: Applications/Java/PetPortal/1.0.6
  environment: Environments/Dev/Tomcat-Dev-AsCode
  #orchestrators:
  #  - parallel-by-deployment-group
  #  - sequential-by-container
  onSuccessPolicy: ARCHIVE


